package com.example.testmqtt.model

import android.app.LauncherActivity
import android.os.Parcelable
import androidx.room.Embedded
import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.Relation
import kotlinx.parcelize.Parcelize

@Parcelize
@Entity(tableName = "topic_table")
data class Topic(
    @PrimaryKey(autoGenerate = true)
    val idTopic: Int,
    val name:String,
    val path:String,
    val type:Boolean,
    val serverId: Int,
    val messages:String,
    val lastValue:String
    ):Parcelable

data class ServerAndTopics(
    @Embedded val server: Server,
    @Relation(
        parentColumn = "id",
        entityColumn = "serverId"
    )
    val topic:List<Topic>
)
/*@Parcelize
@Entity(tableName = "server_table")
data class Server(
    @PrimaryKey(autoGenerate = true)
    val id: Int, // <- 'id' is the primary key which will be autogenerated by the Room library.
    val name: String,
    val address: String,
    val topics: List<Topic>
): Parcelable*/

